name: Count Lines Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: vinod1002/reusable-workflows/.github/workflows/line-counter.yaml@main
    with:
      file_path: 'sample.txt' 
