name: Call Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    runs-on: self-hosted
    steps:
      - name: Call reusable workflow
        uses: vinod1002/reusable-workflows/.github/workflows/reusable-hello-world.yml@main
        with:
          who-to-greet: 'From customer-workflow'
