name: Install Python
 
on:
  workflow_dispatch:
 
jobs:
  call-reusable-workflow:
    uses: vinod1002/reusable-workflows/.github/workflows/python.yaml@main
    with:
      python-dependencies: 'pytest'
