name: Call Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: vinod1002/reusable-workflows/.github/workflows/hello-world.yaml@main
    with: 
      who-to-greet: 'From Master-Blender'
